title: KANTAPONG SIRIBUNCHAPORN
logo: /assets/img/logo.png
description: >
  Email: j_job_j@hotmail.com
  <br>
  Address: Bangkok, Thailand

theme: jekyll-theme-minimal
#color-scheme: auto-deafualt-dark
